component_depth: 1
languages: 
- java
exclude:
- ./bin/.*
- ./bin/ca/.*
- ./bin/ca/bc/.*
- ./bin/ca/bc/webarts/.*
- ./bin/ca/bc/webarts/tools/.*
- ./bin/ca/bc/webarts/widgets/.*
- ./bin/ca/bc/webarts/widgets/dnd/.*
- ./bin/com/.*
- ./bin/com/jcraft/.*
- ./bin/com/jcraft/jogg/.*
- ./bin/com/jcraft/jorbis/.*
- ./bin/kiwi/.*
- ./bin/kiwi/event/.*
- ./bin/kiwi/text/.*
- ./bin/kiwi/ui/.*
- ./bin/kiwi/util/.*
- ./bin/net/.*
- ./bin/net/roarsoftware/.*
- ./bin/net/roarsoftware/lastfm/.*
- ./bin/net/roarsoftware/lastfm/scrobble/.*
- ./bin/net/roarsoftware/util/.*
- ./bin/net/roarsoftware/xml/.*
- ./bin/org/.*
- ./bin/org/jconfig/.*
- ./bin/org/jconfig/event/.*
- ./docs/.*
- ./docs/ca/.*
- ./docs/ca/bc/.*
- ./docs/ca/bc/webarts/.*
- ./docs/ca/bc/webarts/class-use/.*
- ./docs/ca/bc/webarts/tools/.*
- ./docs/ca/bc/webarts/tools/class-use/.*
- ./docs/ca/bc/webarts/widgets/.*
- ./docs/ca/bc/webarts/widgets/class-use/.*
- ./docs/ca/bc/webarts/widgets/dnd/.*
- ./docs/ca/bc/webarts/widgets/dnd/class-use/.*
- ./docs/com/.*
- ./docs/com/jcraft/.*
- ./docs/com/jcraft/jogg/.*
- ./docs/com/jcraft/jogg/class-use/.*
- ./docs/com/jcraft/jorbis/.*
- ./docs/com/jcraft/jorbis/class-use/.*
- ./docs/kiwi/.*
- ./docs/kiwi/class-use/.*
- ./docs/kiwi/event/.*
- ./docs/kiwi/event/class-use/.*
- ./docs/kiwi/text/.*
- ./docs/kiwi/text/class-use/.*
- ./docs/kiwi/ui/.*
- ./docs/kiwi/ui/class-use/.*
- ./docs/kiwi/util/.*
- ./docs/kiwi/util/class-use/.*
- ./docs/org/.*
- ./docs/org/jconfig/.*
- ./docs/org/jconfig/class-use/.*
- ./lib/.*
